name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5092c2fa36da8bb916ef4eb48381ff2523292d0d190325f1aabf01013c992a77"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
