name = "Create'a Colony 1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab64d4eaa2726e244af615b0856e0cfcf8fb2f5ab31ad35cec6bf9b9f573e3bf"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
