name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9197316e07d5566a36472c5ea11b1d9d244e5146a4f558024663fc3981d1600"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
