name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc5cafd64c00e3b098db4ed63c58d06ee55d23a157b72ec98c42ca3c18a54c0"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
