name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d286f059d026f7b7b56343a01bec18be464ee414579cbd90315c4b08aba04290"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
