name = "Cogworks"
author = "namgeftobang"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dde414e3a30b93104df338dd50f32ee6fc84f3003818694b7ebf45cd7c696c4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
