name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "792211a0d17e6c745805d6ec12fd44db4503e15616ce916d53c58a82fbe890c2"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
