name = "Create'a Colony 1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70453b259ab8433dd7b83a3ae14616e854ab551a9aea2326c06dd5f6575a9b31"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
