name = "Cogworks"
author = "namgeftobang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccd93c285b7a47eafb442349cc021b6b568f13116f0a32b40e95ac3665fba22c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
